import { useEffect } from "react";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function Disclaimer() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const goBack = () => {
    window.history.back();
  };

  return (
    <div className="min-h-screen bg-suku-black text-suku-text-primary">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-24">
        <Button 
          onClick={goBack}
          variant="ghost"
          className="mb-8 text-suku-text-secondary hover:text-suku-red"
        >
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back
        </Button>

        <div className="prose prose-invert prose-lg max-w-none">
          <h1 className="text-4xl font-bold text-white mb-8">🔒 Disclaimer Policy</h1>
          
          <div className="text-suku-text-muted mb-8">
            <p><strong>Brought to you by AI Masters World</strong></p>
            <p><strong>Last Updated:</strong> July 19, 2025</p>
          </div>

          <p className="text-suku-text-secondary leading-relaxed mb-8">
            Please read this disclaimer carefully before using the SukuSuku.ai platform ("Service") operated by AI Masters World ("we", "us", or "our").
          </p>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-white mb-6">1. No Responsibility for AI-Generated Content</h2>
            <p className="text-suku-text-secondary leading-relaxed">
              SukuSuku.ai uses artificial intelligence to generate content such as scripts, stories, posters, voiceovers, music, and video. All output is created algorithmically and does not reflect the views, policies, or opinions of AI Masters World. We are not responsible for the content generated by users through the platform.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-white mb-6">2. Copyright and Originality</h2>
            <p className="text-suku-text-secondary leading-relaxed">
              Users are solely responsible for ensuring that the AI-generated content they use, share, or publish does not violate any third-party intellectual property rights, including but not limited to copyright laws, trademarks, or plagiarism regulations. While we strive to help generate original content, we do not guarantee exclusivity or the absence of similarity to existing material.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-white mb-6">3. Ownership of Content</h2>
            <p className="text-suku-text-secondary leading-relaxed">
              To the extent permitted under Indian law, users may use, modify, or publish content generated by SukuSuku.ai for personal, educational, or commercial purposes. However, AI Masters World makes no warranties regarding the originality, uniqueness, or proprietary nature of such content. Users must exercise their own legal diligence when using the output.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-white mb-6">4. Platform Limitations and Third-Party Policies</h2>
            <p className="text-suku-text-secondary leading-relaxed">
              AI Masters World is not liable for the rejection or restriction of AI-generated content by third-party platforms, publishers, marketplaces, or content stores. It is the user's responsibility to comply with the policies of any platform where they choose to publish or share content created through SukuSuku.ai.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-white mb-6">5. No Warranty</h2>
            <p className="text-suku-text-secondary leading-relaxed">
              SukuSuku.ai is provided "as-is" and "as-available". We do not guarantee that the service will meet your expectations or that the results will be accurate, complete, or free from error. All creative outputs are generated algorithmically and may require further human review, editing, or validation.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-white mb-6">6. Limitation of Liability</h2>
            <p className="text-suku-text-secondary leading-relaxed">
              Under no circumstances shall AI Masters World be liable for any direct, indirect, incidental, special, or consequential damages arising from your use of the SukuSuku.ai service, the content generated by it, or any actions taken based on such content.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-white mb-6">7. User Responsibility</h2>
            <p className="text-suku-text-secondary leading-relaxed">
              You agree that you are solely responsible for reviewing, editing, and ensuring the legal and ethical compliance of the content generated through our platform. We strongly recommend exercising due diligence and, where necessary, seeking legal advice before publishing or distributing AI-generated content.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-white mb-6">8. Governing Law</h2>
            <p className="text-suku-text-secondary leading-relaxed">
              This Disclaimer shall be governed and interpreted in accordance with the laws of Bengaluru, Karnataka, India, without regard to its conflict of law principles.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-white mb-6">9. Changes to this Disclaimer</h2>
            <p className="text-suku-text-secondary leading-relaxed">
              We may update this Disclaimer from time to time. It is your responsibility to check this page periodically for changes. Continued use of the SukuSuku.ai platform after any such changes constitutes your acceptance of the updated terms.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}